version: '3'

services:
  web-server:
    build:
      context: .
      dockerfile: compose/web_server/Dockerfile
    image: web_server
    container_name: web_server
    platform: linux/x86_64
    volumes:
      - ".:/app:z"
    ports:
      - "8000:8000"
    command: /start
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/api-db
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
